jean-zay-users/jean-zay-doc

README.md
Here is a suggestion to make the scope of this collaborative repository more explicit.
=> Better define the scope of the repo

README.md
Add section how to access in interactive mode
=> Add how to use interactive mode

README.md, access-procedure.md, limitations.md, tips-and-tricks.md
Close #4.
If anyone has a chance to look at it (for example maybe @mdiazmel?) and has comments, let me know!
=> Restructure doc in separate files

tips-and-tricks.md
I did not open an issue for this, since it was very quick, but I figured it might help some people who are not necessarily familiar with the ssh tips.
=> Add SSH tips

tips-and-tricks.md
With some small restructuring of the other sections.
=> Add miniconda install instructions.

README.md, limitations.md
- add link to examples in README
- add more details about docker image support
=> Minor tweaks

access-procedure.md
Added procedure for non French users. @lesteve
=> Added procedure step for non French users (#26)

README.md
Small PR to make the gitter chat more visible
=> readme: add gitter to useful links

access-procedure.md
=> Added procedure to add IP addresses to the original declaration

tips-and-tricks.md
Added tip to auto requeue a job than ran into the QoS time limit.
=> Tip: Auto requeue on job timeouts

access-procedure.md
I think logging in through RENATER allows to have some fields automatically filled like "Directeur de la structure de recherche".
=> Add EDARI registration link through RENATER.

docs/access-procedure.md, docs/index.md, docs/tips-and-tricks.md, mkdocs.yml
It allowed me to look at the doc with some kind of fresh new eyes so most of the changes are not really related to mkdocs.
=> A few enhancements after looking at doc generated with mkdocs.

docs/tips-and-tricks.md
@lesteve can you check that the instructions I gave are working for you?
=> Added tensorboard-dev tip

docs/examples/tf/tf_distributed/mnist_example.py
=> TF distributed with NCCL

docs/tips-and-tricks.md
=> Using available datasets

docs/tips-and-tricks.md
=> Fix bullet point list and add admonitions to section

docs/tips-and-tricks.md
=> fixed a command typo

docs/examples/dask/xarray/README.md, docs/examples/dask/xarray/example.py, docs/examples/dask/xarray/example.slurm, mkdocs.yml
This PR adds an example of how to do distributed computation using xarray/dask on Jean-Zay.
=> Adds dask/xarray example

docs/index.md
Recent (2023) scripts for finetuning and inference of LLM on Jean Zay.
Recent (2024) scripts for pretraining an LLM on Jean Zay, either with DeepSpeed or Megatron-DS.
=> example scripts for LLM

docs/index.md
Follow-up of https://github.com/jean-zay-users/jean-zay-doc/pull/100#issuecomment-2252274661.
=> Create and tidy section for external links
